FROM stuartleeks/aspnet-cached


COPY project.json /app/project.json
COPY NuGet.config /app/NuGet.config
WORKDIR /app
RUN ["dotnet", "restore"]
COPY . /app

RUN ["dotnet", "build"]

EXPOSE 5000
ENTRYPOINT ["dotnet", "run"]
